version: "3"

services:
    node14-web-app:
      build:
        context: .
        dockerfile: Dockerfile
      tty: true
      stdin_open: true
      volumes:
        - ./src:/usr/src/app
      ports:
        - "3000:3000"