# https://www.cloudbees.com/blog/using-docker-compose-for-php-development

version: '3'

# /usr/bin/docker-compose -f /home/demos/Git/docktest/server10/server.yml up -d
# /usr/bin/docker-compose -f /home/demos/Git/docktest/server10/server.yml -p server10 stop nginx web postgres

# ok
# http://localhost:3000/


services:
  nginx:
    image: nginx
    ports:
      - "3000:80"
    #volumes:
    #  - ./nginx.conf:/etc/nginx/conf.d/default.conf
  web:
    build: .
    ports:
      - "9000:9000"
    volumes:
      - .:/app
      - /app/vendor
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://todoapp@postgres/todos
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: todoapp
      POSTGRES_DB: todos
