# https://www.cloudsavvyit.com/12978/how-to-quickly-deploy-wordpress-as-a-docker-container/
# https://hub.docker.com/_/wordpress


version: '3.5'

services:

  wpblog:
    image: wordpress:5.8.2-php8.0-apache
#    build:
#      context: .
#      dockerfile: Dockerfile
    #user: 1000:1000
    volumes:
      - ./src:/var/www/html
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: wpdb:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    depends_on:
      - wpdb


  wpdb:
    image: mysql:5.7
    #user: 1000:1000
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    volumes:
      - ./db:/var/lib/mysql


volumes:
  wpdb:
  wpblog: