version: '3.5'

services:

  espocrmdb_fresh:
    image: mysql:8
    container_name: espocrmdb_fresh
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: espocrm
      MYSQL_USER: espocrm
      MYSQL_PASSWORD: database_password
    volumes:
      #- mysql:/var/lib/mysql
      - ./espoDumpDev.sql:/docker-entrypoint-initdb.d/dump.sql
    restart: always
    ports:
      - "3307:3306"


  espocrm_fresh:
    image: espocrm/espocrm:7.1.9
    container_name: espocrm_fresh
    environment:
      ESPOCRM_DATABASE_HOST: espocrmdb_fresh
      ESPOCRM_DATABASE_USER: espocrm
      ESPOCRM_DATABASE_PASSWORD: database_password
      ESPOCRM_ADMIN_USERNAME: admin
      ESPOCRM_ADMIN_PASSWORD: password
      ESPOCRM_SITE_URL: "http://localhost:8080"
    volumes:
      #- espocrm:/var/www/html
      #- ./espocrm_dir:/var/www/html
      - ./html:/var/www/html
    restart: always
    ports:
      - "8083:80"

#  espocrm-daemon:
#    image: espocrm/espocrm
#    container_name: espocrm-daemon
#    volumes:
#      - espocrm:/var/www/html
#    restart: always
#    entrypoint: docker-daemon.sh
#
#  espocrm-websocket:
#    image: espocrm/espocrm
#    container_name: espocrm-websocket
#    environment:
#      ESPOCRM_CONFIG_USE_WEB_SOCKET: "true"
#      ESPOCRM_CONFIG_WEB_SOCKET_URL: "ws://localhost:8081"
#      ESPOCRM_CONFIG_WEB_SOCKET_ZERO_M_Q_SUBSCRIBER_DSN: "tcp://*:7777"
#      ESPOCRM_CONFIG_WEB_SOCKET_ZERO_M_Q_SUBMISSION_DSN: "tcp://espocrm-websocket:7777"
#    volumes:
#      - espocrm:/var/www/html
#    restart: always
#    entrypoint: docker-websocket.sh
#    ports:
#      - 8081:8080

volumes:
  espocrmdb_fresh:
  espocrm_fresh:
  #  external: true

