
# http://localhost:8089/  adminer
# http://localhost:8080/index.html nginx
# OK

version: '3.7'
services:

  # https://www.cakedc.com/rochamarcelo/2020/07/20/a-quick-cakephp-local-environment-with-docker
  # https://github.com/webdevops/Dockerfile
  # https://webdevops.io/projects/dockerfiles/
  # https://github.com/webdevops/Dockerfile/tree/master/docker

  # http://localhost:8089/  adminer

  adminer:
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 512M
        reservations:
          cpus: 0.25
          memory: 128M
    user: "1000:1000"
    container_name: project_name_adminer
    image: adminer
    #environment:
    #  - ${UID}
    #  - ${GID}
    restart: always
    ports:
      - "8089:8080"


  php-fpm:
    container_name: myapp-webserver
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./app:/usr/share/nginx/html

  mysql:
    image: mysql:5.7
    container_name: myapp-mysql
    working_dir: /app
    volumes:
      - .:/app
      - ./tmp/data/mysql_db:/var/lib/mysql
    #env_file:
    #  - mysql.env
    command: mysqld --character-set-server=utf8 --init-connect='SET NAMES UTF8;'
    ports:
      - "3306:3306"
    links:
      - adminer


