
version: '3'

networks:
  openldap:
    name: openldap

services:
  openldap:
    image: bitnami/openldap:latest
    restart: unless-stopped
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - LDAP_ORGANISATION=company
      - LDAP_DOMAIN=company.network
      - LDAP_ROOT=dc=company,dc=network
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=password
    networks:
      - openldap
    volumes:
      - 'openldap_data:/bitnami/openldap'

  openldap-ui:
    image: wheelybird/ldap-user-manager:latest
    restart: unless-stopped
    ports:
      - "8082:80"
    environment:
      - SERVER_HOSTNAME=localhost:8082
      - LDAP_URI=ldap://openldap
      - LDAP_BASE_DN=dc=company,dc=network
      - LDAP_ADMINS_GROUP=admins
      - LDAP_ADMIN_BIND_DN=cn=admin,dc=company,dc=network
      - LDAP_ADMIN_BIND_PWD=password
      - LDAP_IGNORE_CERT_ERRORS=true
      - NO_HTTPS=true
    networks:
      - openldap
    depends_on:
      - openldap

volumes:
  openldap_data:
    driver: local
