version: '3.5'

services:

  wpblog:
    image: wpblog
    build:
      context: .
      dockerfile: Dockerfile
    #user: 1000:1000
    volumes:
      - ./src:/var/www/html
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: wpdb:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    depends_on:
      - wpdb


  wpdb:
    image: mysql:5.7
    #user: 1000:1000
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    volumes:
      - ./db:/var/lib/mysql