# Use root/example as user/password credentials
version: '3.1'
services:

#  db-mariadb:
#    image: mariadb
#    restart: always
#    environment:
#      MARIADB_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  web:
    image: php:7.4.23-apache
    container_name: my-apache-php-app
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html

# Use postgres/example user/password credentials
#  db-postgres:
#    image: postgres
#    restart: always
#    environment:
#      POSTGRES_PASSWORD: example
#
#  mongo:
#    image: mongo
#    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
#
#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - "8081:8081"
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example
#      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/


# ------------------------------------------
# cakephp-2.10.24.zip
# cakephp-3.10.4.zip
# CodeIgniter-3.1.12.zip

# https://github.com/cakephp/cakephp/tags
# https://github.com/bcit-ci/CodeIgniter/tags
# ------------------------------------------