# ok
# http://localhost:8080/wp-admin/install.php

version: '3.1'

services:

  wordpress:
    image: wordpress
    # Restart mode: In case the container stops running
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      #WORDPRESS_CONFIG_EXTRA: |
      #    define('WP_DEBUG', boolval(getenv('WP_DEBUG')));

  db:
    image: mysql:5.7
    restart: always
    links:
      - wordpress
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
