# http://localhost:9008/wp-admin/install.php
# OK

version: "3"

services:

  # WordPress image based on Apache
  wordpress:
    build:
      context: ../srv_keycloak_wp/docker
      dockerfile: ../srv_keycloak_wp/docker/Dockerfile-wp
    depends_on:
      - my_database
    image: wordpress
    restart: always
    # restart: unless-stopped
    working_dir: /var/www/html
    # env_file: .env
    ports:
      - "9008:80"
    environment:
      WORDPRESS_DB_HOST: my_database:3306
      WORDPRESS_DB_USER: blabla
      WORDPRESS_DB_PASSWORD: blabla
      WORDPRESS_DB_NAME: my_wp_database
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_DEBUG: 1
      
      #WORDPRESS_CONFIG_EXTRA: |
      #  define( 'WP_DEBUG', true );     
      #  define( 'WP_DEBUG_DISPLAY', true );
      #  define( 'WP_DEBUG_LOG', true );
      # define( 'SAVEQUERIES', true );
      #NEXT_VAR: false
      
      #LIVE_URL: https://project1.com
      #DEV_URL: http://dev.project1.com
    volumes:
      - ./src:/var/www/html
    #  - ./docker/php.conf.ini:/usr/local/etc/php/conf.d/custom.ini
    #  - ./wp-content:/var/www/html/wp-content

  # MySQL Database image
  my_database:
    image: mysql:5.7
    restart: always
    # env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: blabla
      MYSQL_DATABASE: my_wp_database
      MYSQL_USER: blabla
      MYSQL_PASSWORD: blabla
    #ports:
    #  - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql: {}