# sudo docker-compose -f keycloak.yml up -d

# docker-compose -f keycloak.yml up -d
# docker-compose -f keycloak.yml -p test stop postgresql keycloak-2 keycloak-3 keycloak-1

# OK

# https://github.com/bitnami/bitnami-docker-keycloak

# http://localhost:9011/
# http://localhost:9011/auth/

version: "2"

services:
  postgresql:
    image: "docker.io/bitnami/postgresql:11"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - "postgresql_data:/bitnami/postgresql"
    links:
      - keycloak-1
  keycloak-1:
    image: docker.io/bitnami/keycloak:latest
    ports:
      - "9011:8080"
    environment:
      - KEYCLOAK_CREATE_ADMIN_USER=true
      #- KEYCLOAK_ADMIN_USER=user
      #- KEYCLOAK_ADMIN_PASSWORD=bitnami
      #- KEYCLOAK_MANAGEMENT_USER=manager
      #- KEYCLOAK_MANAGEMENT_PASSWORD=bitnami1
#      - KEYCLOAK_JGROUPS_DISCOVERY_PROTOCOL=JDBC_PING
#      - 'KEYCLOAK_JGROUPS_DISCOVERY_PROPERTIES=datasource_jndi_name=>java:jboss/datasources/KeycloakDS, initialize_sql=>"CREATE TABLE IF NOT EXISTS JGROUPSPING ( own_addr varchar(200) NOT NULL, cluster_name varchar(200) NOT NULL, created timestamp default current_timestamp, ping_data BYTEA, constraint PK_JGROUPSPING PRIMARY KEY (own_addr, cluster_name))"'
#      - KEYCLOAK_CACHE_OWNERS_COUNT=3
#      - KEYCLOAK_AUTH_CACHE_OWNERS_COUNT=3
    #depends_on:
    #  - postgresql
volumes:
  postgresql_data:
    driver: local