# /usr/bin/docker-compose -f /home/demos/Git/test/keycloak_debian.yml up -d
# /usr/bin/docker-compose -f /home/demos/Git/test/keycloak_debian.yml -p test stop keycloak postgresql
# /usr/bin/docker-compose -f /home/demos/Git/test/keycloak_debian.yml -p test stop keycloak postgresql
# /usr/bin/docker-compose -f /home/demos/Git/test/keycloak_debian.yml -p test down --remove-orphans

# http://localhost:81/auth/
# OK

version: "2"

services:
  postgresql:
    image: "docker.io/bitnami/postgresql:11"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - "postgresql_data:/bitnami/postgresql"
  keycloak:
    image: docker.io/bitnami/keycloak:latest
    ports:
      - "81:8080"
    environment:
      - KEYCLOAK_CREATE_ADMIN_USER=true
      #- KEYCLOAK_ADMIN_USER=user
      #- KEYCLOAK_ADMIN_PASSWORD=bitnami
      #- KEYCLOAK_MANAGEMENT_USER=manager
      #- KEYCLOAK_MANAGEMENT_PASSWORD=bitnami1
    depends_on:
      - postgresql
volumes:
  postgresql_data:
    driver: local