# https://www.youtube.com/watch?v=w2_Dx8pd43w
# https://docs.docker.com/config/containers/container-networking/
# https://docs.docker.com/config/containers/container-networking/
# https://docs.docker.com/network/iptables/
# https://docs.docker.com/network/none/

# docker exec -it keyloack_wordpress_1 bash
# hostname -d
# hostname -f

# apt install net-tools
# netstat -tulpen
# netstat -tulpn | grep LISTEN

# apt install nmap
# nmap -sTU 127.0.0.1
# nmap -sTU localhost

# docker network ls
# docker ps
# ip addr show

# curl -I http://localhost:9008
# curl -I http://localhost:9011
# cURL error 7: Failed to connect to localhost port 9011: Connection refused

# docker exec -it keycloak_container bash
# docker exec -it -u 0 keycloak_container bash  # as root
# curl -v http://localhost:9011  > Connection refused
# curl -Ivk http://localhost:9011  > Connection refused
# curl -I http://localhost:80 > OK

# using 8080:80 everywhere > WARNING: Host is already in use by another container
# lsof -i -P -n | grep LISTEN
# lsof -i -P -n | grep :80
# docker ps -a
# lsof -i tcp:8080
# lsof -i tcp:80

# clear containers volumes images networks
# docker rm -f $(docker ps -aq)
# docker volume rm $(docker volume ls -q)
# docker rmi -f $(docker images -a -q)
# docker network rm $(docker network ls | tail -n+2 | awk '{if($2 !~ /bridge|none|host/){ print $1 }}')

# docker network ls
# docker network inspect keyloack_keycloaknetwork
# docker network inspect keyloack_wordpressnetwork

# docker info
# netstat -a | grep LISTEN

# http://localhost:9011/auth/
# http://localhost:9008/wp-admin/install.php

# OK

version: "2"
services:

  postgresql:
    image: "docker.io/bitnami/postgresql:11"
    links:
      - keycloak
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - "postgresql_data:/bitnami/postgresql"
    networks:
      - keycloaknetwork

  keycloak:
    #domainname: keycloak.local
    #hostname: keycloak
    container_name: keycloak_container
    image: docker.io/bitnami/keycloak:latest
    ports:
      - "9011:8080"
    environment:
      - KEYCLOAK_CREATE_ADMIN_USER=true
      #- KEYCLOAK_ADMIN_USER=user
      #- KEYCLOAK_ADMIN_PASSWORD=bitnami
      #- KEYCLOAK_MANAGEMENT_USER=manager
      #- KEYCLOAK_MANAGEMENT_PASSWORD=bitnami1
    #depends_on:
    #  - postgresql
    networks:
      - keycloaknetwork

  db:
    image: mysql:5.7
    links:
      - wordpress
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    networks:
      - wordpressnetwork

  wordpress:
    #domainname: wordpress.local
    container_name: wordpress_container
    #hostname: wordpress
    image: wordpress
    restart: always
    ports:
    #  - "127.0.0.1:9008:80"
      - "9008:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    networks:
      - wordpressnetwork

volumes:
  postgresql_data:
    driver: local

networks:
  keycloaknetwork:
  wordpressnetwork:
