# http://localhost:8070/   phpmyadmin
# http://localhost:8089/  Adminer
# UID=${UID} GID=${GID} docker-compose up
# http://localhost:8080/index.html nginx

#  /usr/bin/docker-compose -f /home/demos/GitDocker/docker_playground/srv_lamp/server.yml -p srv_lamp down --remove-orphans
# OK

version: '2.3'
services:

  # https://blog.sylo.space/guide-to-install-nginx-php-mariadb-phpmyadmin-in-docker/
  web:
    image: nginx:alpine
    mem_limit: 512m
    mem_reservation: 128M
    cpuset: 0-3
    ports:
      - "8080:80"
    volumes:
      - ./app:/usr/share/nginx/html

  # mariadb
  db:
    container_name: project_name_mariadb
    image: mariadb:10.4 #v10.5.8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data/db:/var/lib/mysql

  # phpmyadmin http://localhost:8070/
  dbadmin:
    container_name: project_name_phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root # Remove line for production
      PMA_PASSWORD: root # Remove line for production
    depends_on:
      - db
    ports:
      - "8070:80"

  # adminer http://localhost:8089/
  adminer:
    container_name: project_name_adminer
    image: adminer
    restart: always
    ports:
      - "8089:8080"
    links:
      - db
  # http://localhost:8089/
  # http://localhost:8089/?server=db&username=root # user: root / pass root

