FROM wordpress:php7.3-apache
 
# Install xdebug
RUN pecl install xdebug && docker-php-ext-enable xdebug
 
# Install Less for WP-CLI
RUN apt-get update && apt-get -y install less

## php/config/php.ini ##
#This file is created automatically by the docker build

# Install the 2.4 version of xdebug that's compatible with php7
#RUN pecl install -o -f xdebug-2.4.0

#COPY config/php.ini /usr/local/etc/php/
 
# Install WP-CLI
#RUN curl -s -o /usr/local/bin/wp \
#    https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
#    && chmod +x /usr/local/bin/wp