# http://localhost:8081/auth/

version: '2'
services:
  keycloack:
    tty: true
    image: jboss/keycloak:1.9.1.Final
 #   image: jboss/keycloak:2.2.1.Final
 #   image: jboss/keycloak:3.4.3.Final
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - "8081:8080"