version: '3'

# ok
# https://hub.docker.com/_/mysql

# /usr/bin/docker-compose -f /home/demos/Git/docktest/server8/mysql1.yml up -d
# /usr/bin/docker-compose -f /home/demos/Git/docktest/server8/mysql1.yml -p server8 stop db

# docker ps
# docker exec -it b72e6511b13c bash

services:
  db:
    image: mariadb:10.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    user: "1000:1000"
    #command: --innodb-flush-method=O_DSYNC --innodb-use-native-aio=0 --log_bin=ON
    #volumes:
    #  - ./db:/var/lib/mysql