version: '3.3'
services:
  # change mariadb image into mysql
  mysql:
    #image: mariadb:10
    image: mysql:5.7
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: example
    volumes:
      - mysql:/var/lib/mysql


