version: "3"

services:
    node-web-app:
      build:
        context: .
        dockerfile: Dockerfile
      tty: true
      stdin_open: true
      volumes:
        - ./app:/usr/src/app
      ports:
        - "8000:8000"

# npm install -g npm@9.6.1