# https://stackoverflow.com/questions/36249744/interactive-shell-using-docker-compose

version: '3'

services:
  frontend:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
#    volumes:
#      - /app/node_modules
#      - .:/app