# docker run -it ubuntu bash
# docker run -it ubuntu:latest   bash
# docker container ls -a
# docker run --name some-mysql -e MYSQL_ROOT_PASSWORD=my-secret-pw -d mysql:5.6.24
# docker run --name some-mysql -e MYSQL_ROOT_PASSWORD=my-secret-pw -d mysql:5.7
# docker run -d -t -i centos /bin/bash
# docker run -d -t -i centos:7 /bin/bash
# docker ps -a
# sudo docker run --rm -it --entrypoint /bin/sh starter

# Dockerfile
# RUN chmod +x ./app.sh
# CMD ["./app.sh"]
# sudo docker run --rm -it starter /bin/sh

# OK

version: "2"

services:
  test-app:
    image: ubuntu:latest
    build:
      context: docker-ubuntu
      dockerfile: docker-ubuntu/Dockerfile
    entrypoint: /bin/sh
    stdin_open: true # docker run -i
    tty: true        # docker run -t
