version: "3.7"

# https://github.com/phpmyadmin/docker/issues/293
# to Enter in docker
# docker exec -it some-mariadb bash

# ok
# http://localhost:8086/


services:
  db:
    image: mariadb
    container_name: MariaDB
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      TZ: 'Europe/Berlin'
    ports:
      - "9306:3306"
    volumes:
      - './database:/var/lib/mysql'

  myphpadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: MyPhpAdmin
    restart: always
    links:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: test
      TZ: 'Europe/Berlin'
    ports:
      - "8086:80"