version: "3"

# /usr/bin/docker-compose -f /home/demos/Git/docktest/server6/server-network1.yml up -d
# /usr/bin/docker-compose -f /home/demos/Git/docktest/server6/server-network1.yml -p server6 stop phpmyadmin mysqldb

services:
  mysqldb:
    image: mysql:5.7
    environment:
      #MYSQL_ROOT_PASSWORD=password
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    networks:
      - mysql-network
    links:
      - phpmyadmin
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:8080"
    environment:
      PMA_HOST: mysqldb
    networks:
      - mysql-network

networks:
  mysql-network:
    # Use a custom driver
    # driver: custom-driver-1

volumes:
  db:
