version: "3"

# /usr/bin/docker-compose -f /home/demos/Git/docktest/server6/server-network1.yml up -d
# /usr/bin/docker-compose -f /home/demos/Git/docktest/server6/server-network1.yml -p server6 stop phpmyadmin mysqldb

services:
  mysqldb:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - mysql-network

  phpmyadmin:
    image: phpmyadmin:5.1-apache
    environment:
      - PMA_HOST=mysqldb
    networks:
      - mysql-network

networks:
  mysql-network:
    # Use a custom driver
    # driver: custom-driver-1