version: "3.7"

services:

  db:
    image: mariadb:10.5.8
    networks:
      - private
    command: --max-allowed-packet=64MB
    volumes:
      - "./db:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=<>
      - MYSQL_USER=matomo
      - MYSQL_PASSWORD=<>
      - MYSQL_DATABASE=matomo

  app:
    image: matomo:4.1.1-fpm
    depends_on:
      - db
    networks:
      - private
    environment:
      - MATOMO_DATABASE_ADAPTER=mysql
      - MATOMO_DATABASE_HOST=db
      - MATOMO_DATABASE_TABLES_PREFIX=matomo_
      - MATOMO_DATABASE_USERNAME=matomo
      - MATOMO_DATABASE_PASSWORD=<>
      - MATOMO_DATABASE_DBNAME=matomo
    volumes:
      #- "${DIRECTORY}/config:/var/www/html/config"
      #- "${DIRECTORY}/logs:/var/www/html/logs"
      - "./matomo:/var/www/html"

  web:
    image: nginx:1.19.7
    depends_on:
      - db
      - app
    networks:
      - private
      - proxy
    volumes:
      - "./matomo:/var/www/html:ro"
      # see https://github.com/matomo-org/matomo-nginx
      - "./nginx.conf:/etc/nginx/conf.d/default.conf:ro"
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.services.matomo.loadbalancer.server.port: "80"
        traefik.http.routers.matomo.rule: "Host(`${HOST_NAME}`)"
        traefik.http.routers.matomo.entrypoints: "web-secured"
        traefik.http.routers.matomo.tls.certresolver: "mytlschallenge"

networks:
  private:
  proxy:
    external: true

volumes:
  matomo:
