version: "3"

services:

  db:
    image: mariadb:10.11
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - db:/var/lib/mysql:Z
    env_file:
      - ./db.env
    networks:
      - matomo-network

  app:
    container_name: matomo
    image: matomo
    restart: always
    volumes:
      #     - ./config:/var/www/html/config:z
      #     - ./logs:/var/www/html/logs:z
      - matomo:/var/www/html:z
    environment:
      - MATOMO_DATABASE_HOST=db
    env_file:
      - ./db.env
    expose:
      - 8080
    ports:
      - "80:8080"
    networks:
      - matomo-network
    #  - reverse-proxy-network

  web:
    image: nginx:1.19.7
    depends_on:
      - db
      - app
    networks:
      - matomo-network
    volumes:
      - "./matomo:/var/www/html:ro"
      # see https://github.com/matomo-org/matomo-nginx
      - "./nginx.conf:/etc/nginx/conf.d/default.conf:ro"


volumes:
  db:
  matomo:

networks:
  matomo-network:
  #reverse-proxy-network:
  #  external: true

